services:
  - type: web
    name: gsp-cems-by-shawn
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CEMS_PLANT_CODE
        value: S1602755
      - key: CEMS_TIMEOUT
        value: 35
